=== FixMyBerlin/rsv-dossier/data/schema/geometry.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GeoJSON FeatureCollection RSV",
  "type": "object",
  "required": ["type", "features", "bbox", "crs", "id"],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "crs": {
      "type": "object",
      "properties": {
        "type": { "const": "name" },
        "properties": {
          "properties": {
            "name": {
              "const": "urn:ogc:def:crs:OGC:1.3:CRS84"
            }
          }
        }
      }
    },
    "type": {
      "type": "string",
      "const": "FeatureCollection"
    },
    "features": {
      "type": "array",
      "items": {
        "title": "GeoJSON Feature",
        "type": "object",
        "required": ["type", "properties", "geometry", "bbox"],
        "properties": {
          "type": {
            "const": "Feature"
          },
          "id": {
            "type": ["number", "string"]
          },
          "properties": {
            "type": "object",
            "required": [
              "id",
              "detail_level",
              "state",
              "id_rsv",
              "planning_phase",
              "variant",
              "discarded",
              "length",
              "stand"
            ],
            "properties": {
              "id": { "type": "string" },
              "detail_level": {
                "type": "string"
              },
              "state": {
                "type": "string",
                "enum": ["idea", "agreement_process", "planning", "done"]
              },
              "id_rsv": { "type": "string" },
              "planning_phase": {
                "oneOf": [
                  {
                    "type": "string",
                    "enum": [
                      "pilot",
                      "preliminary",
                      "design",
                      "approval",
                      "execution",
                      "building"
                    ]
                  },
                  { "type": "null" }
                ]
              },
              "variant": {
                "type": ["string", "null"]
              },
              "discarded": {
                "type": "boolean"
              },
              "stand": {
                "type": "string",
                "pattern": "^[0-9]{2}.[0-9]{2}.[0-9]{4}$"
              },
              "length": { "type": "number" },
              "description:planning_phase": {
                "type": ["string", "null"]
              }
            }
          },
          "geometry": {
            "title": "GeoJSON MultiLineString",
            "type": "object",
            "required": ["type", "coordinates"],
            "properties": {
              "type": {
                "const": "MultiLineString"
              },
              "coordinates": {
                "type": "array",
                "items": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "items": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          },
          "bbox": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
              "type": "number"
            }
          }
        }
      }
    },
    "bbox": {
      "type": "array",
      "minItems": 4,
      "items": {
        "type": "number"
      }
    }
  },
  "if": {
    "properties": {
      "features": {
        "items": {
          "properties": {
            "properties": { "properties": { "state": { "const": "done" } } }
          }
        }
      }
    }
  },
  "then": {
    "properties": {
      "features": {
        "items": {
          "properties": {
            "properties": {
              "properties": { "planning_phase": { "const": null } }
            }
          }
        }
      }
    }
  }
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/6_hamburg.json
{
  "id": "6-hamburg",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [9.478504, 53.468862, 9.882698, 53.596653],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "state": "planning",
        "id_rsv": "6-hamburg",
        "planning_phase": "preliminary",
        "detail_level": "rough",
        "variant": null,
        "discarded": false,
        "description:planning_phase": null,
        "stand": "20.04.2022",
        "length": 57553.85212355369
      },
      "bbox": [9.478504, 53.468862, 9.882698, 53.596653],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [9.710679, 53.468958],
            [9.713498, 53.470389],
            [9.714139, 53.471781],
            [9.718689, 53.47241],
            [9.723174, 53.47569],
            [9.739226, 53.479218],
            [9.74714, 53.479561],
            [9.746979, 53.487091],
            [9.74762, 53.490199],
            [9.766621, 53.490166],
            [9.794178, 53.494451],
            [9.802175, 53.494135],
            [9.805753, 53.500926],
            [9.811466, 53.513395],
            [9.812013, 53.521358],
            [9.821459, 53.521231],
            [9.82458, 53.525399],
            [9.822015, 53.526237],
            [9.82334, 53.527305],
            [9.831248, 53.530836],
            [9.839449, 53.529023],
            [9.842655, 53.529988],
            [9.843553, 53.531716],
            [9.842869, 53.536594],
            [9.850307, 53.536467],
            [9.864199, 53.534536],
            [9.877269, 53.533634],
            [9.87868, 53.532313],
            [9.878509, 53.520447],
            [9.879834, 53.518363],
            [9.882698, 53.517676],
            [9.87992, 53.516482],
            [9.880988, 53.514753],
            [9.879877, 53.513686],
            [9.874106, 53.512517],
            [9.872311, 53.509339],
            [9.875731, 53.508983],
            [9.877312, 53.502755],
            [9.879877, 53.501636],
            [9.877825, 53.500237],
            [9.877868, 53.498992],
            [9.875303, 53.498534],
            [9.874662, 53.492355],
            [9.867908, 53.489226],
            [9.867438, 53.485793],
            [9.862479, 53.483758],
            [9.860556, 53.481596],
            [9.862454, 53.479899],
            [9.863081, 53.476831],
            [9.85756, 53.47681]
          ],
          [
            [9.478504, 53.596653],
            [9.485662, 53.595232],
            [9.510638, 53.578034],
            [9.521578, 53.569884],
            [9.526584, 53.566489],
            [9.534758, 53.562597],
            [9.540528, 53.559624],
            [9.547191, 53.555709],
            [9.556238, 53.547415],
            [9.558222, 53.54563],
            [9.561153, 53.541357],
            [9.564921, 53.534033],
            [9.565597, 53.527123],
            [9.572276, 53.51342],
            [9.577181, 53.50887],
            [9.585016, 53.506761],
            [9.589015, 53.504651],
            [9.589401, 53.503462],
            [9.591723, 53.503328],
            [9.59427, 53.501717],
            [9.593658, 53.499933],
            [9.602783, 53.496327],
            [9.608974, 53.493584],
            [9.610683, 53.494256],
            [9.613392, 53.493085],
            [9.614682, 53.491647],
            [9.638865, 53.481805],
            [9.656737, 53.474675],
            [9.674664, 53.472304],
            [9.690534, 53.470239],
            [9.706083, 53.468862],
            [9.716171, 53.469091],
            [9.77163, 53.472008],
            [9.795275, 53.473423],
            [9.826802, 53.475155],
            [9.854104, 53.474404],
            [9.854083, 53.476257],
            [9.857442, 53.476743]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/30_baden_wuerttemberg.json
{
  "id": "30-baden-wuerttemberg",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [7.591621, 47.546755, 7.87616, 47.591564],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "detail_level": "corridor",
        "state": "idea",
        "id_rsv": "30-baden-wuerttemberg",
        "planning_phase": null,
        "variant": "Vorzugstrasse",
        "discarded": false,
        "stand": "07.06.2022",
        "length": 23587.598,
        "description:planning_phase": null
      },
      "bbox": [7.591621, 47.546755, 7.87616, 47.591564],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [7.87616, 47.591564],
            [7.816078, 47.588554],
            [7.786896, 47.557053],
            [7.729465, 47.546755],
            [7.684833, 47.551158],
            [7.654106, 47.554981],
            [7.591621, 47.554055]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/7_baden_wuerttemberg.json
{
  "id": "7-baden-wuerttemberg",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    8.34836520128735, 48.9899184354538, 8.47024657436891, 49.0465980479245
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "detail_level": "rough",
        "state": "planning",
        "id_rsv": "7-baden-wuerttemberg",
        "planning_phase": "pilot",
        "variant": "Vorzugstrasse",
        "discarded": false,
        "stand": "02.06.2022",
        "length": 23804.959,
        "description:planning_phase": null
      },
      "bbox": [
        8.348365201287349, 48.98991843545378, 8.470246574368907,
        49.046598047924526
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [8.38046488711068, 48.992129911489585],
            [8.38570498376339, 48.99109839403816],
            [8.390179535045744, 48.99056113690705],
            [8.393192590621052, 48.991291805187046],
            [8.396628333680344, 48.98991843545378],
            [8.417931578177535, 48.99556814875071],
            [8.43627191646201, 49.00020939264515],
            [8.43959200895057, 49.000725059715904],
            [8.44365308385642, 48.99986561163177],
            [8.451578730043638, 48.999263989148666],
            [8.456098313406596, 48.99969372023526],
            [8.460617896769557, 49.00175637784055],
            [8.467541737945528, 49.005477906445925],
            [8.470246574368907, 49.008588321018586],
            [8.464032147244835, 49.01013504594359],
            [8.463172443887752, 49.01271281404379],
            [8.452778220918038, 49.01602075422486],
            [8.440247021032159, 49.018598217577654],
            [8.435956691897754, 49.01969359908819],
            [8.432686748771827, 49.021156083757596],
            [8.430667469338928, 49.0227057739426],
            [8.420813631336525, 49.02821956822046],
            [8.402735297884686, 49.03869785140481],
            [8.403259307549956, 49.041961128184404],
            [8.400115249558333, 49.04385029582643],
            [8.396971191566708, 49.046598047924526],
            [8.392517109411909, 49.046426317866576],
            [8.388637186284948, 49.0463102655777],
            [8.387015007926564, 49.045739391703876],
            [8.378630853282234, 49.04178938211289],
            [8.373976173677455, 49.04102188460852],
            [8.371470752465383, 49.04182695161667],
            [8.369751345751213, 49.042760813019605],
            [8.363434572989382, 49.038526094064274],
            [8.359369404258034, 49.03379716683624],
            [8.356651104119441, 49.029202001024984],
            [8.354753446389456, 49.026383857107135],
            [8.348365201287349, 49.02123460971299],
            [8.349548316859709, 49.01413052960851],
            [8.35442406304204, 49.01242819203766],
            [8.362648558491477, 49.00536582310001],
            [8.366054621315737, 49.002443911392646],
            [8.368593816588312, 48.999932085098855],
            [8.377844838784325, 48.992989493051475],
            [8.38046488711068, 48.992129911489585]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/rs7_nordrhein_westfalen.json
{
  "id": "rs7-nordrhein-westfalen",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    6.92869566350497, 51.4646875413971, 6.99574616946811, 51.5223517068917
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "id_rsv": "RS7",
        "state": "agreement_process",
        "detail_level": "approximated",
        "variant": "Vorzugstrasse",
        "length": 8791.472,
        "discarded": false,
        "stand": "01.01.2022",
        "planning_phase": null
      },
      "bbox": [
        6.928695663504974, 51.46468754139711, 6.995746169468115,
        51.52235170689174
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [6.995317987347466, 51.46468754139711],
            [6.995746169468115, 51.46595786410668],
            [6.99530828866908, 51.46850753768828],
            [6.993579666473902, 51.46985368010919],
            [6.990880637001057, 51.471202928917414],
            [6.989164594839976, 51.47200724059371],
            [6.98920707346251, 51.47419252932494],
            [6.987436414383535, 51.475183032802455],
            [6.98576639137093, 51.4760024773482],
            [6.985328619846836, 51.4770013650282],
            [6.985120387086313, 51.478721953545275],
            [6.984766786487432, 51.48031016863496],
            [6.983926489257175, 51.481346736013144],
            [6.98267212600974, 51.48234087846727],
            [6.980952584172551, 51.48316145103926],
            [6.980201608512011, 51.483799981769984],
            [6.980242879077893, 51.484412856942456],
            [6.980577609447667, 51.48548150005579],
            [6.978748681290141, 51.48585831845969],
            [6.977311320120495, 51.48633560788306],
            [6.975334851110468, 51.486973085945486],
            [6.971086963634238, 51.48844708372611],
            [6.967285999060998, 51.48874653661931],
            [6.963909064177592, 51.48969968384807],
            [6.960783043846468, 51.49106591262747],
            [6.957256608847318, 51.49284177913748],
            [6.954766025785334, 51.495636681935665],
            [6.952621725869959, 51.497223765193134],
            [6.95050616853097, 51.49869593176587],
            [6.950298831458943, 51.49974161688226],
            [6.949929458326174, 51.50078403628821],
            [6.948781297542009, 51.502230397553525],
            [6.947481580535127, 51.5029695473243],
            [6.94441695200378, 51.504022634444],
            [6.943057555179689, 51.5046640894481],
            [6.942651352955711, 51.505021523439495],
            [6.943414212611864, 51.50657163186298],
            [6.944032175341705, 51.50779872047897],
            [6.944637487394316, 51.508539196498226],
            [6.944821600336352, 51.509173078140975],
            [6.942434680082086, 51.51084003496962],
            [6.939348950086394, 51.511883594681954],
            [6.936272090965772, 51.51414463734935],
            [6.932185816349353, 51.5153144160383],
            [6.930680037442221, 51.51766487536089],
            [6.929479244234013, 51.521077254492965],
            [6.928695663504974, 51.52235170689174]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/3_nordrhein_westfalen.json
{
  "type": "FeatureCollection",
  "id": "3-nordrhein-westfalen",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    6.95960216568961, 50.776404511097, 7.16006736458641, 50.9382521373113
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "length": 33738.34205881348,
        "detail_level": "corridor",
        "id_rsv": "3-nordrhein-westfalen",
        "state": "agreement_process",
        "planning_phase": null,
        "variant": "Vorzugstrasse",
        "discarded": false,
        "stand": "27.06.2022",
        "description:planning_phase": null
      },
      "bbox": [
        6.959602165689605, 50.776404511096956, 7.160067364586408,
        50.938252137311288
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [6.959602165689605, 50.938252137311288],
            [6.974668976816877, 50.932458543597875],
            [6.986926721462797, 50.912175281291105],
            [7.016038864996857, 50.898970312774509],
            [7.047193965971898, 50.895749020544017],
            [7.059962449978062, 50.885117175140898],
            [7.040554354288689, 50.863201477113613],
            [7.034936221325982, 50.856753722237961],
            [7.034425481965733, 50.830631196913451],
            [7.043108051089926, 50.805139582420551],
            [7.054344317015354, 50.786415360990851],
            [7.075795370145713, 50.776404511096956]
          ],
          [
            [7.040554354288689, 50.863201477113613],
            [7.086010157350644, 50.857720942307317],
            [7.160067364586408, 50.814821581126829]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/7_hamburg.json
{
  "id": "7-hamburg",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    9.71232231210928, 53.2810600220712, 10.0178981708302, 53.4370070968245
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "state": "idea",
        "id_rsv": "7-hamburg",
        "planning_phase": null,
        "detail_level": "corridor",
        "variant": null,
        "discarded": false,
        "description:planning_phase": null,
        "stand": "20.04.2022",
        "length": 27463.691575129324
      },
      "bbox": [
        9.712322312109285, 53.28106002207117, 10.017898170830223,
        53.43700709682448
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [9.712322312109285, 53.28106002207117],
            [9.881338510358978, 53.32923764837392],
            [10.017898170830223, 53.43700709682448]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/frm6_hessen.json
{
  "id": "frm6-hessen",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    8.67212347707556, 50.1108799721448, 8.77310325408052, 50.4335371428843
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "id_rsv": "frm6-hessen",
        "state": "agreement_process",
        "planning_phase": null,
        "detail_level": "corridor",
        "variant": "Vorzugstrasse",
        "length": 39012.329526586764,
        "discarded": false,
        "description:planning_phase": null,
        "stand": "07.06.2022"
      },
      "bbox": [
        8.672123477075557, 50.1108799721448, 8.773103254080523,
        50.43353714288435
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [8.68243275359701, 50.1108799721448],
            [8.741148627386586, 50.1808778477495],
            [8.773103254080523, 50.23010207952742],
            [8.770729725053359, 50.27914277878308],
            [8.754091273687985, 50.33775979194285],
            [8.734961730154463, 50.36337870019319],
            [8.672123477075557, 50.43353714288435]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/1_bayern.json
{
  "id": "1_bayern",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [11.5785367032267, 48.1462389314442, 11.669749, 48.270993],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "detail_level": "corridor",
        "id_rsv": "1-bayern",
        "state": "planning",
        "planning_phase": "preliminary",
        "variant": "Vorzugstrasse",
        "length": 21263.535,
        "stand": "27.06.2022",
        "discarded": false
      },
      "bbox": [11.57853670322673, 48.14623893144424, 11.669749, 48.270993],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [11.602208, 48.249168],
            [11.592273, 48.270993]
          ],
          [
            [11.57853670322673, 48.14623893144424],
            [11.58598476192743, 48.16313272427922],
            [11.58275726982379, 48.1912766856319],
            [11.587206, 48.221998],
            [11.597171, 48.229257],
            [11.60213, 48.249231],
            [11.613737, 48.250615],
            [11.630063, 48.249519],
            [11.631159, 48.252199],
            [11.637832, 48.251471],
            [11.647592, 48.260535],
            [11.658298, 48.262527],
            [11.669749, 48.260954]
          ],
          [
            [11.658308, 48.262574],
            [11.665047, 48.27048]
          ]
        ]
      }
    }
  ]
}
