=== FixMyBerlin/rsv-dossier/data/schema/geometry.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GeoJSON FeatureCollection RSV",
  "type": "object",
  "required": ["type", "features", "bbox", "crs", "id"],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string"
    },
    "crs": {
      "type": "object",
      "properties": {
        "type": { "const": "name" },
        "properties": {
          "properties": {
            "name": {
              "const": "urn:ogc:def:crs:OGC:1.3:CRS84"
            }
          }
        }
      }
    },
    "type": {
      "type": "string",
      "const": "FeatureCollection"
    },
    "features": {
      "type": "array",
      "items": {
        "title": "GeoJSON Feature",
        "type": "object",
        "required": ["type", "properties", "geometry", "bbox"],
        "properties": {
          "type": {
            "const": "Feature"
          },
          "id": {
            "type": ["number", "string"]
          },
          "properties": {
            "type": "object",
            "required": [
              "id",
              "detail_level",
              "state",
              "id_rsv",
              "planning_phase",
              "variant",
              "discarded",
              "length",
              "stand"
            ],
            "properties": {
              "id": { "type": "string" },
              "detail_level": {
                "type": "string"
              },
              "state": {
                "type": "string",
                "enum": ["idea", "agreement_process", "planning", "done"]
              },
              "id_rsv": { "type": "string" },
              "planning_phase": {
                "oneOf": [
                  {
                    "type": "string",
                    "enum": [
                      "pilot",
                      "preliminary",
                      "design",
                      "approval",
                      "execution",
                      "building"
                    ]
                  },
                  { "type": "null" }
                ]
              },
              "variant": {
                "type": ["string", "null"]
              },
              "discarded": {
                "type": "boolean"
              },
              "stand": {
                "type": "string",
                "pattern": "^[0-9]{2}.[0-9]{2}.[0-9]{4}$"
              },
              "length": { "type": "number" },
              "description:planning_phase": {
                "type": ["string", "null"]
              }
            }
          },
          "geometry": {
            "title": "GeoJSON MultiLineString",
            "type": "object",
            "required": ["type", "coordinates"],
            "properties": {
              "type": {
                "const": "MultiLineString"
              },
              "coordinates": {
                "type": "array",
                "items": {
                  "type": "array",
                  "minItems": 2,
                  "items": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "items": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          },
          "bbox": {
            "type": "array",
            "minItems": 4,
            "maxItems": 4,
            "items": {
              "type": "number"
            }
          }
        }
      }
    },
    "bbox": {
      "type": "array",
      "minItems": 4,
      "items": {
        "type": "number"
      }
    }
  },
  "if": {
    "properties": {
      "features": {
        "items": {
          "properties": {
            "properties": { "properties": { "state": { "const": "done" } } }
          }
        }
      }
    }
  },
  "then": {
    "properties": {
      "features": {
        "items": {
          "properties": {
            "properties": {
              "properties": { "planning_phase": { "const": null } }
            }
          }
        }
      }
    }
  }
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/rs17_baden_wuerttemberg.json
{
  "type": "FeatureCollection",
  "id": "rs17-baden-wuerttemberg",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    8.87076563869863, 48.7523899054795, 9.06586177808219, 48.8262738013699
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "detail_level": "rough",
        "state": "agreement_process",
        "id_rsv": "RS17",
        "planning_phase": "preliminary",
        "variant": "Vorzugstrasse",
        "discarded": false,
        "stand": "07.06.2022",
        "length": 20703.207,
        "description:planning_phase": null
      },
      "bbox": [
        8.870765638698632, 48.752389905479475, 9.065861778082192,
        48.826273801369851
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [9.065861778082192, 48.826273801369851],
            [9.057744320547945, 48.822365395890401],
            [9.021311332702991, 48.808045792510654],
            [9.016501018812473, 48.802102193213358],
            [8.936842, 48.768591],
            [8.876670525342469, 48.752389905479475],
            [8.870765638698632, 48.753221381164408]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/rs14_baden_wuerttemberg.json
{
  "id": "rs14-baden-wuerttemberg",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [9.50542, 48.683083, 9.76081, 48.716094],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "detail_level": "corridor",
        "state": "planning",
        "id_rsv": "RS14",
        "planning_phase": null,
        "variant": null,
        "discarded": false,
        "stand": "07.06.2022",
        "length": 19906.352,
        "description:planning_phase": null
      },
      "bbox": [9.50542, 48.683083, 9.76081, 48.716094],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [9.76081, 48.683083],
            [9.738372, 48.690416],
            [9.708336, 48.698812],
            [9.652475, 48.703543],
            [9.62408, 48.71214],
            [9.605049, 48.705859],
            [9.586028, 48.704839],
            [9.556086, 48.715068],
            [9.525351, 48.716094],
            [9.50542, 48.713018]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/frm2_hessen.json
{
  "id": "frm2-hessen",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    8.48432601166193, 49.9249538847202, 8.59380326592056, 50.0230387454606
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "id_rsv": "frm2-hessen",
        "state": "agreement_process",
        "planning_phase": null,
        "detail_level": "approximated",
        "variant": "Vorzugstrasse",
        "length": 14269.568252915209,
        "discarded": false,
        "description:planning_phase": "Politische Beschlüsse",
        "stand": "07.06.2022"
      },
      "bbox": [
        8.48432601166193, 49.9249538847202, 8.593803265920556, 50.01876940842946
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [8.593803265920556, 50.01876940842946],
            [8.592133782120655, 50.017522989996785],
            [8.580739671586423, 50.01595918675786],
            [8.577310376182917, 50.013826645772326],
            [8.578416600506628, 50.012404899202316],
            [8.577420998615288, 50.0122627222318],
            [8.573549213482297, 50.00664639543157],
            [8.56834995916085, 49.99363390208648],
            [8.564810041324971, 49.98076015719161],
            [8.566026888081055, 49.980333344212255],
            [8.561270123489095, 49.973005797624225],
            [8.551867216737543, 49.965961764199854],
            [8.549986635387233, 49.9653925043568],
            [8.549322900793005, 49.9640404852481],
            [8.533611664302683, 49.951474354727246],
            [8.524590804095919, 49.94840624464004],
            [8.505646997661714, 49.9452550092118],
            [8.499203526085452, 49.941523016419076],
            [8.49095588246784, 49.93322866396914],
            [8.489409449289537, 49.932150293278205],
            [8.487839766471529, 49.93006827058143],
            [8.487158385959225, 49.92802258728178],
            [8.485785328665603, 49.926084756896174],
            [8.48432601166193, 49.9249538847202]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "2",
        "id_rsv": "frm2-hessen",
        "state": "agreement_process",
        "planning_phase": null,
        "detail_level": "approximated",
        "variant": "Alternativetrasse",
        "length": 10455.501545657264,
        "discarded": false,
        "description:planning_phase": "Politische Beschlüsse",
        "stand": "07.06.2022"
      },
      "bbox": [
        8.538207154585635, 49.96539250435681, 8.592133782120653,
        50.02303874546058
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [8.577310376182917, 50.013826645772326],
            [8.575960818290648, 50.01401546703647],
            [8.562731771709378, 50.014603993372845],
            [8.559271867218891, 50.02140421926354],
            [8.5582542482511, 50.0222541798267],
            [8.556117248418744, 50.02290798541142],
            [8.553878486689603, 50.02297336548051],
            [8.552453820134698, 50.022711844670326],
            [8.548790391850654, 50.022711844670326],
            [8.538207154585635, 50.02303874546058]
          ],
          [
            [8.592133782120653, 50.017522989996785],
            [8.573925580355068, 49.99059935104547],
            [8.573213247077614, 49.98595401734761],
            [8.571890342419488, 49.986542887295926],
            [8.566293438096643, 49.97875613544398],
            [8.567311057064432, 49.97685833264067],
            [8.565275819128853, 49.97640023109379],
            [8.564665247748179, 49.976662003940326],
            [8.561270123489095, 49.973005797624225]
          ],
          [
            [8.549986635387233, 49.96539250435681],
            [8.550418582199118, 49.96854638346295],
            [8.555934251800092, 49.96900864335661],
            [8.555710200831625, 49.97168807632614],
            [8.558356010147884, 49.971131749824536],
            [8.558557206756422, 49.970973566348526]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/9_nordrhein_westfalen.json
{
  "id": "9-nordrhein-westfalen",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [
    6.89780481238658, 51.0820659021538, 6.91056998364509, 51.1316965665994
  ],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "id_rsv": "RS-Monheim",
        "state": "planning",
        "detail_level": "approximated",
        "variant": "Vorzugstrasse",
        "length": 5965.901,
        "discarded": false,
        "stand": "01.01.2022",
        "planning_phase": "approval"
      },
      "bbox": [
        6.897804812386578, 51.08206590215384, 6.910569983645095,
        51.1316965665994
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [6.905242726198005, 51.090701684820736],
            [6.90546394168824, 51.09026205268998],
            [6.90595186308774, 51.08900082010046],
            [6.906572608742192, 51.08747057310082],
            [6.907036216869629, 51.08636093757028],
            [6.907672816759753, 51.08486344449914],
            [6.908232888352762, 51.08390746506408],
            [6.908652937623841, 51.08338316267444],
            [6.910569983645095, 51.08206590215384]
          ],
          [
            [6.904303230093658, 51.09273157119605],
            [6.905171823242627, 51.092946773536724],
            [6.904821455088189, 51.094363980646435],
            [6.904396193121256, 51.09611522017951],
            [6.903962426074718, 51.09802925620625],
            [6.903596255915586, 51.09942710468524],
            [6.902952944841452, 51.10264681607032],
            [6.902799175551208, 51.103653018689585],
            [6.903566544801289, 51.1048788313432],
            [6.903341046127748, 51.10555673119872],
            [6.902653502011457, 51.106866914561465],
            [6.902367368254189, 51.108537027552245],
            [6.902391032640228, 51.110351506807305],
            [6.901285837441725, 51.112690253243144],
            [6.901013995197223, 51.11421172673333],
            [6.900894409751774, 51.11519895875351],
            [6.899751609162188, 51.11563318750906],
            [6.899547104646581, 51.116631404037626],
            [6.899302526525802, 51.11792956032378],
            [6.898918119265987, 51.119676038012514],
            [6.898809114426382, 51.12032535417975],
            [6.898821542612012, 51.12063451195748],
            [6.898700409509729, 51.12119973122106],
            [6.89892217596903, 51.124439201474026],
            [6.898514793158009, 51.125795863877265],
            [6.898076371753042, 51.12732599836189],
            [6.897804812386578, 51.12838994869791],
            [6.897847434196651, 51.12852902744689],
            [6.898317539235318, 51.128921432661066],
            [6.900050251434949, 51.129063035804236],
            [6.903606393506402, 51.12967544729785],
            [6.905642481308579, 51.130717922605385],
            [6.907535906844175, 51.1316965665994]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "2",
        "id_rsv": "RS-Monheim",
        "state": "done",
        "detail_level": "exact",
        "variant": "Vorzugstrasse",
        "length": 243.466,
        "discarded": false,
        "stand": "01.01.2022",
        "planning_phase": null
      },
      "bbox": [
        6.90444849102231, 51.090690529267206, 6.905249306957381,
        51.09281958697332
      ],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [6.905249306957381, 51.090690529267206],
            [6.905078788841004, 51.09109849037274],
            [6.904554101588345, 51.09247076079983],
            [6.90444849102231, 51.09281958697332]
          ]
        ]
      }
    }
  ]
}

=== FixMyBerlin/rsv-dossier/src/radschnellwege/geometry/rs3_baden_wuerttemberg.json
{
  "id": "rs3-baden-wuerttemberg",
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" }
  },
  "bbox": [9.159626, 49.118207, 9.21516722114723, 49.232695],
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1",
        "detail_level": "rough",
        "state": "planning",
        "id_rsv": "RS3",
        "planning_phase": "design",
        "variant": "Trasse 1.1  \"Neckar\"",
        "discarded": false,
        "stand": "07.06.2022",
        "length": 17596.977,
        "description:planning_phase": null
      },
      "bbox": [9.159626, 49.118207, 9.215167221147231, 49.232695],
      "geometry": {
        "type": "MultiLineString",
        "coordinates": [
          [
            [9.17031, 49.23039],
            [9.175615, 49.231897],
            [9.178499, 49.232695],
            [9.191214, 49.231478],
            [9.20259258755699, 49.219082812796785],
            [9.205339986492673, 49.214527297361],
            [9.207981716238523, 49.21293967060097],
            [9.209355415706364, 49.20921199868233],
            [9.21220848383188, 49.20631250397591],
            [9.212631160591215, 49.20417229167158],
            [9.211046122743708, 49.20092727697101],
            [9.213476514109887, 49.197267749625674],
            [9.214744544387894, 49.19395322704158],
            [9.2150615519574, 49.19036224360404],
            [9.215167221147231, 49.186563804385074],
            [9.21379352167939, 49.18421553246523],
            [9.20787604704869, 49.18290321432362],
            [9.202803925936657, 49.18055476868311],
            [9.203526, 49.156431],
            [9.196059, 49.126888],
            [9.190165, 49.12135],
            [9.174522, 49.120316],
            [9.173749, 49.12273],
            [9.159626, 49.118207]
          ]
        ]
      }
    }
  ]
}
